title: ### Rlmt: R wrapper of the Linear Mixed Models Toolbox (LMT)
description: For animal and plant breeding!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
      repository_url: https://github.com/qsmei/Rlmt
